version: "3.9"

networks:
  network:
    name: "${PLATFORM_NAME}-network"

services:
  web:
    build:
      context: ../mtt-php72-apache/
      dockerfile: Dockerfile-web
    image: mtt-dev/php:7.2-apache
    container_name: ${PLATFORM_NAME}-web
    ports:
      - "8080:80"
    environment:
      - MTT_ENABLE_DEBUG=YES
      - MTT_DB_TYPE=postgres
      - MTT_DB_HOST=db
      - MTT_DB_NAME=mtt
      - MTT_DB_USER=mtt
      - MTT_DB_PASSWORD=mtt
      - MTT_DB_PREFIX=mtt_
    volumes:
      - ../../../src:/var/www/html
      - ../mtt-php72-apache/php-mtt.ini:/usr/local/etc/php/conf.d/php-mtt.ini
      - ../mtt-php72-apache/php-opcache.ini:/usr/local/etc/php/conf.d/php-opcache.ini
    depends_on:
      - db
    networks:
      - network

  db:
    # do not use alpine image due to missing locales
    image: postgres:10.0
    container_name: ${PLATFORM_NAME}-db
    environment:
      POSTGRES_PASSWORD: mtt
      POSTGRES_USER: mtt
      POSTGRES_DB: mtt
    volumes:
      - ../_postgres10/db_data:/var/lib/postgresql/data
    networks:
      - network
