version: "3.9"

networks:
  network:
    name: "${PLATFORM_NAME}-network"

services:
  web:
    build:
      context: ../mtt-php72-apache/
      dockerfile: Dockerfile-web
    image: mtt-dev/php:7.2-apache
    container_name: ${PLATFORM_NAME}-web
    ports:
      - "8080:80"
    environment:
      - MTT_ENABLE_DEBUG=YES
      - MTT_DB_TYPE=mysql
      - MTT_DB_HOST=db
      - MTT_DB_NAME=mytinytodo
      - MTT_DB_USER=mtt
      - MTT_DB_PASSWORD=mtt
      - MTT_DB_PREFIX=mtt_
      - MTT_DB_DRIVER=mysqli
    volumes:
      - ../../../src:/var/www/html
      - ../mtt-php72-apache/php-mtt.ini:/usr/local/etc/php/conf.d/php-mtt.ini
      - ../mtt-php72-apache/php-opcache.ini:/usr/local/etc/php/conf.d/php-opcache.ini
    depends_on:
      - db
    networks:
      - network

  db:
    image: mariadb:10.5
    container_name: ${PLATFORM_NAME}-db
    #restart: always
    environment:
      MARIADB_ROOT_PASSWORD: JustForDev
      MARIADB_USER: mtt
      MARIADB_PASSWORD: mtt
      MARIADB_DATABASE: mytinytodo
    volumes:
      - ../_mariadb105/my.cnf:/etc/mysql/conf.d/my.cnf
      - ../_mariadb105/db_data:/var/lib/mysql
    networks:
      - network
