version: "3.9"

networks:
  network:
    name: "${PLATFORM_NAME}-network"

services:
  web:
    build:
      context: ../mtt-php71-apache/
      dockerfile: Dockerfile-web
    image: mytinytodo-dev:php7.1-apache
    container_name: ${PLATFORM_NAME}-web
    ports:
      - "8080:80"
    environment:
      - MTT_ENABLE_DEBUG=YES
      - MTT_DB_TYPE=mysql
      - MTT_DB_HOST=db
      - MTT_DB=mytinytodo
      - MTT_DB_USER=mtt
      - MTT_DB_PASSWORD=mtt
      - MTT_DB_PREFIX=mtt_
      - MTT_DB_DRIVER=mysqli
    volumes:
      - ../../../src:/var/www/html
    depends_on:
      - db
    networks:
      - network

  db:
    build:
      context: ../_mariadb105
      dockerfile: Dockerfile-db
    image: mytinytodo-dev:mariadb10.5
    container_name: ${PLATFORM_NAME}-db
    #restart: always
    environment:
      MARIADB_ROOT_PASSWORD: JustForDev
      MARIADB_USER: mtt
      MARIADB_PASSWORD: mtt
      MARIADB_DATABASE: mytinytodo
    volumes:
      - ../_mariadb105/db_data:/var/lib/mysql
    networks:
      - network
