version: '3'
services:
  web:
    build: ./
    image: mtt-php5.4-apache
    container_name: mtt-php54-apache
    ports:
    - "8080:80"
    volumes:
    - ../../../src:/var/www/html
    - ./php-mtt.ini:/usr/local/etc/php/conf.d/php-mtt.ini
