version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    image: mytinytodo-dev:php8.1-apache
    container_name: ${PLATFORM_NAME}-web
    ports:
      - "8080:80"
    environment:
      - MTT_ENABLE_DEBUG=YES
    volumes:
      - ../../../src:/var/www/html
