services:
  web:
    build: ./
    image: mytinytodo-dev:php7.2-apache
    container_name: mtt-dev-php72-apache
    ports:
    - "8080:80"
    volumes:
    - ../../../src:/var/www/html
    - ./php-mtt.ini:/usr/local/etc/php/conf.d/php-mtt.ini
    - ./php-opcache.ini:/usr/local/etc/php/conf.d/php-opcache.ini
