services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    image: mytinytodo-dev:php7.2-apache
    container_name: ${PLATFORM_NAME}-web
    ports:
    - "8080:80"
    environment:
    - MTT_ENABLE_DEBUG=YES
    - MTT_DB_TYPE=sqlite
    volumes:
    - ../../../src:/var/www/html
    - ../../../tests:/var/www/tests
    - ./php-mtt.ini:/usr/local/etc/php/conf.d/php-mtt.ini
    - ./php-opcache.ini:/usr/local/etc/php/conf.d/php-opcache.ini
