version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    image: mtt-dev/php:8.0-apache
    container_name: ${PLATFORM_NAME}-web
    ports:
      - "8080:80"
    environment:
      - MTT_ENABLE_DEBUG=YES
      - MTT_DB_TYPE=sqlite
    volumes:
      - ../../../src:/var/www/html
