version: '3'
services:
  web:
    build: ./
    image: mytinytodo-dev:php5.6-apache
    container_name: mtt-dev-php56-apache
    ports:
    - "8080:80"
    environment:
    - MTT_ENABLE_DEBUG=YES
    volumes:
    - ../../../src:/var/www/html
    - ./php-mtt.ini:/usr/local/etc/php/conf.d/php-mtt.ini
    - ./php-opcache.ini:/usr/local/etc/php/conf.d/php-opcache.ini
