services:
  web:
    build: ./
    image: mytinytodo-dev:php7.0-apache
    container_name: mtt-dev-php70-apache
    ports:
    - "8080:80"
    environment:
    - MTT_ENABLE_DEBUG=YES
    - MTT_DB_TYPE=sqlite
    volumes:
    - ../../../src:/var/www/html
    - ./php-mtt.ini:/usr/local/etc/php/conf.d/php-mtt.ini
    - ./php-opcache.ini:/usr/local/etc/php/conf.d/php-opcache.ini
